# CircleCI configuration file
version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: dockerized-voter-statistics
          path: .

workflows:
  example-workflow:
    jobs:
      - example-job