# CircleCI configuration file
version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
     - image: cimg/base:stable
    steps:
      - run: sudo docker build -t dockerized-voter-statistics .

workflows:
  deploy_app:
    jobs:
      - build