# CircleCI configuration file
version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - run: npm run docker-build

workflows:
  deploy_app:
    jobs:
      - build