# CircleCI configuration file
version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
     - image: docker:17.05.0-ce-git
    steps:
      - run: docker build . -t dockerized-voter-statistics && docker run -p 3000:3000 -d dockerized-voter-statistics

workflows:
  deploy_app:
    jobs:
      - build